### ISSUE TITLE
 It is assumed..

### ISSUE THREAD

**Issue by PsycoYT** [Luka967/Cigar#10]
This is supposed to be created by the smoothrender theme..

Is the smoothrender just like agar.io?ç

And a little doubt , how to connect To my server to see the progress?

NICE WORK!

**Comment by Luka967** [comment]
Smooth cell rendering is in progress.

To connect to your server do the same as for the old Cigar;
add this
```html
<option value="IP:PORT">NAME</option>
```
to the gamemode options (after line 57 in index.html) and change IP, PORT and NAME.

**Comment by PsycoYT** [comment]
When I give to be spectator the game restarts, how do I? and i cant play or be spectator

**Comment by Luka967** [comment]
Make sure you have the latest `index.html`.

**Comment by PsycoYT** [comment]
yes.. http://ogar.pw/www/



ERROR
![image](https://cloud.githubusercontent.com/assets/24230169/21612579/95b0b88c-d1b0-11e6-92b7-2e42e0345389.png)

**Comment by PsycoYT** [comment]
PD : ERROR WHEN PRESS SPECTATOR


`Uncaught TypeError: Cannot set property 'killer' of undefined`

![image](https://cloud.githubusercontent.com/assets/24230169/21612786/4aa3c05e-d1b1-11e6-9eac-ededa0ce9c07.png)

**Comment by Luka967** [comment]
I've forgot to edit `reader.js` to fix an error.

You can replace it now.

**Comment by PsycoYT** [comment]
ok thanks

**Comment by PsycoYT** [comment]
ERROR KILLER IS FIXED 

AND NOW THIS ERROR 👍 

WHEN PRESS SPECTATOR:

`Uncaught TypeError: ((c & 15) << 12) is not a function
`

WHEN PRESS PLAY :

`uncaught ReferenceError: setNick is not defined`

**Comment by Luka967** [comment]
Replace `reader.js` and `index.html`, I've put fixes to them.

**Comment by Luka967** [comment]
Also replace `main_out.js`, just found a bug and fixed it.

**Comment by PsycoYT** [comment]
new bug: 
There are times when you split a lot, some cells are left without a name

**Comment by PsycoYT** [comment]
new bug WTF !


All those green cells are mine and even the camera has been bug and the names are flying wtf

![image](https://cloud.githubusercontent.com/assets/24230169/21613435/01b8a2d0-d1b4-11e6-9fec-3492d83131fd.png)

**Comment by Luka967** [comment]
Replace the `reader.js` already, it still displays a bug.
I've put yet another update to `main_out.js` which should fix this.

**Comment by PsycoYT** [comment]
NEW BUG : 

The division is not well observed, as in cigar

**Comment by Luka967** [comment]
Define "not well observed".

**Comment by PsycoYT** [comment]
Divisions look strange, not like cigar or agar.io, 

Just compare cigar 5 and this cigar 6

**Comment by PsycoYT** [comment]
BUG :  
When I give enough splits,
There are cells behind as if they were no longer mine


![image](https://cloud.githubusercontent.com/assets/24230169/21613882/feb9b4a0-d1b5-11e6-9aa6-82597027df4f.png)

**Comment by PsycoYT** [comment]
PD : THE MOVEMENT OF THE CELL IS REALLY LIKE AGAR.IO , GOOD JOB ;D

**Comment by Luka967** [comment]
Cell splitting is the same for me in both versions.
Yet another `main_out.js` update should finally fix cell disappearing problem

**Comment by PsycoYT** [comment]
you can finish the virus ? please =)

**Comment by PsycoYT** [comment]
features?:
add Smooth Render please =D
change the colors of chat ( with white background the letters cant see )
finish virus
add skins


your client is amazing ! GOOD WORK !

**Comment by Luka967** [comment]
Closing this
