### ISSUE TITLE
auto connect to server

### ISSUE THREAD

**Issue by newcoda** [Luka967/Cigar#100]
is it possible to make it auto-connect to the server without having to choose gamemode? 
i see this in main_out.js 

    var CONNECT_TO,
        SKIN_URL = "./skins/",
        USE_HTTPS = "https:" == wHandle.location.protocol,
            BORDER_DEFAULT = {
            top: -2E3,
            left: -2E3,
            right: 2E3,
            bottom: 2E3
    },

and i add this CONNECT_TO = "127.0.0.1:4444"
since i'm testing on my local machine, but it won't connect. 

    var CONNECT_TO,
        CONNECT_TO = "127.0.0.1:4444"
        SKIN_URL = "./skins/",
        USE_HTTPS = "https:" == wHandle.location.protocol,
            BORDER_DEFAULT = {
            top: -2E3,
            left: -2E3,
            right: 2E3,
            bottom: 2E3
        },

**Comment by FirstCodeReviewer** [comment]
Just try to execute setserver() on DOM ready.
Then finally change the default value of the gamemode selection form.

**Comment by bradennss** [comment]
Or write your own connector with a built in load balancer like myself ;)
