### ISSUE TITLE
Drawing hats

### ISSUE THREAD

**Issue by ArixProject** [Luka967/Cigar#101]
@Luka967 help me plz
![image](https://user-images.githubusercontent.com/29149118/29676190-0d426fe2-8900-11e7-811f-ebbb0a9a0467.png)
![image](https://user-images.githubusercontent.com/29149118/29676205-14ac45a0-8900-11e7-97d0-f60d11547123.png) Where to insert?

**Comment by ArixProject** [comment]
![image](https://user-images.githubusercontent.com/29149118/29676515-f5edc20a-8900-11e7-8fc8-38d68bfc651a.png)
WTF?!
![image](https://user-images.githubusercontent.com/29149118/29676634-3ec93a68-8901-11e7-9eb8-aab9b937dde6.png) I can not play lol

**Comment by hossem123** [comment]
bro you need to understand code first before use it !!!!
use this i make it work with cigar . 
bad english sorry .
[main_out.js.txt](https://github.com/Luka967/Cigar/files/1254387/main_out.js.txt)

**Comment by zettabyte918** [comment]
bro you need to understand code first before use it !!!!
use this i make it work with cigar .
bad english sorry .
[main_out.js.txt](https://github.com/Luka967/Cigar/files/1254390/main_out.js.txt)

**Comment by zettabyte918** [comment]
if u have problem with facebook or u want leveling system with facebook tell me i can help

**Comment by ArixProject** [comment]
thanks )

**Comment by ArixProject** [comment]
I also have a problem with facebook (but I have a domain)

**Comment by zettabyte918** [comment]
what is the problem

**Comment by bradennss** [comment]
Jesus christ, learn JavaScript before you try to fiddle with the client.
