### ISSUE TITLE
how to make color name or other name ?

### ISSUE THREAD

**Issue by ChamForever** [Luka967/Cigar#102]
So how? :D

**Comment by ArixProject** [comment]
lol client sided :D

**Comment by bradennss** [comment]
Definitely client sided.

**Comment by ChamForever** [comment]
okay :((

**Comment by MiraMiPalo** [comment]
client & server side xD

**Comment by Pollogy** [comment]
@MiraMiPalo U know how to make?

**Comment by ArixProject** [comment]
@MiraMiPalo @chewythepig is no't a client sided and server sided :D
![image](https://user-images.githubusercontent.com/29149118/30807840-37c67868-a204-11e7-8744-81c5b990c074.png)

**Comment by MiraMiPalo** [comment]
i thought he was talking about leaderboard xDxD

**Comment by ArixProject** [comment]
:DD

**Comment by ArixProject** [comment]
@MiraMiPalo and leaderboard no client sided

**Comment by ChamForever** [comment]
@ArixProject thanks))

**Comment by bradennss** [comment]
@ArixProject I also thought you were referring to the leaderboard, my mistake.
