### ISSUE TITLE
Camera Issues

### ISSUE THREAD

**Issue by FirstCodeReviewer** [Luka967/Cigar#104]
With the new client the view is much smaller than on the old client before the rewrite. Did you lower the area which is beeing displayed? I didnt changed the servers view scale so it could only be any clientsided change.. 
In my oppinnion there is a small difference if you compare the view with 2 cells or 4 cells? Can this be possible? 
Could this be the Problem?
```
        cameraZ += (targetZ * viewMult * mouseZ - cameraZ) / 9;
        cameraZInvd = 1 / cameraZ;
```

old formula was:
`drawZoom += (newDrawZoom * viewMult * mouseZoom - drawZoom) * .11;`

Can you look into that?

**Comment by Luka967** [comment]
The formulas are the same.
A zoom difference between having two and four cells is natural because of square rooting. Check the `targetZ` formula.

**Comment by FirstCodeReviewer** [comment]
Let the Formulas be the same. 
But you cant deny that the Camera is way to near to the Cell than on the old Client before the rewrite.
Also compare the sight of your client and the official client there is also a little difference.
