### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Tetratrix** [Luka967/Cigar#105]
How to separate the skin from the nick, in the input.

I mean: in the input of the nick does not show {skin}, that maybe move it to another site (another input that remains hidden)

I tried, but I did not succeed. You can help?

**Comment by ghost** [comment]
Yea, same can someone help?

**Comment by Tetratrix** [comment]
Please

**Comment by Tetratrix** [comment]
@CodeFlush How to show other player mass is this cigar version?

**Comment by Tetratrix** [comment]
i fix the show mass of other players, any help with skins?

**Comment by Luka967** [comment]
What do you exactly mean? You want the skin in curly braces to be in its own text input?

**Comment by Tetratrix** [comment]
@Luka967 
I want there to be two input, one for the nick and one for the skin.

the input id = "skin" <- there is established the skin code in braces {skin}

the input id = "nick" <- there the nick is set, nothing but the nick

I tried to create another input, and in the php file on the onclick replace the id "#nick" with "#skin", but it has not taken effect

**Comment by Tetratrix** [comment]
@Luka967 practically yes, I want to do what you wrote xD

**Comment by ghost** [comment]
@Luka967 What i want is Different input for skins that braces do not have to be shown in the nick ? 
so, if i want my nick to be Flush and skin to be {poo} I dont have to do {Poo} Flush in the nick box . Thenks! and Ive also heard youre working on a minimap great work bro!

**Comment by zettabyte918** [comment]
lol make it urself ;-;

**Comment by MiraMiPalo** [comment]
@hossemThecoder  If he could do it, he would not ask for help

**Comment by Luka967** [comment]
What @hossemThecoder said. It's unbelievably easy to do it.

**Comment by Tetratrix** [comment]
@Luka967 help me pls, i cant do it

**Comment by ghost** [comment]
@Luka967  Tried this alot but can't crack the code, cigar really needs this. Those brackets are annoying

**Comment by MiraMiPalo** [comment]
just need index.html

**Comment by ghost** [comment]
@MiraMiPalo Can u make it pls, ur great, thx 
and Do u have discord?

**Comment by MiraMiPalo** [comment]
miramipalo#8607

**Comment by Tetratrix** [comment]
@MiraMiPalo Can you help me, i dont have discord, help me pls!!!

**Comment by Tetratrix** [comment]
@CodeFlush can you help me?

**Comment by bradennss** [comment]
you guys are slow

**Comment by Tetratrix** [comment]
@chewythepig can you help me plllssss?

**Comment by mafiakb** [comment]
any help?
