### ISSUE TITLE
Where draw border cell?

### ISSUE THREAD

**Issue by Tetratrix** [Luka967/Cigar#107]
where is the border of the cell drawn?

**Comment by Pollogy** [comment]
I know this but I’m in mobile , I’ll help you tmr

**Comment by Luka967** [comment]
https://github.com/Luka967/Cigar/blob/master/www/assets/js/main_out.js#L982-L983

**Comment by Tetratrix** [comment]
Thanks

**Comment by ghost** [comment]
@Tetratrix Whats ur site?
