### ISSUE TITLE
leaderboard names allign left

### ISSUE THREAD

**Issue by cowpits** [Luka967/Cigar#108]
What's the trick to get the names on the leaderboard to allign left rather than center?

**Comment by Shair17** [comment]
You draw leaderboard with canvas or html?

**Comment by ghost** [comment]
@cowpits, I have this if you are trying to make the leaderboard look like the the Agar.io one , check the last sentence if not.


1) Find (Ctrl+F), in Main Out.js, this : `
    function drawLeaderboard() {`


2) Delete the Code Until : `function drawGrid() {`


3)Copy the Following code : 


------------

    function drawLeaderboard() {
        if (leaderboard.type === NaN) return leaderboard.visible = false;
        if (leaderboard.items.length === 0 || !settings.showNames)
            return leaderboard.visible = false;
        leaderboard.visible = true;
        var canvas = leaderboard.canvas;
        var ctx = canvas.getContext("2d");
        var len = leaderboard.items.length;

        canvas.width = 300;
        canvas.height = leaderboard.type !== "pie" ? 60 + 24 * len : 240;

        ctx.globalAlpha = .4;
        ctx.fillStyle = "#000";
        ctx.fillRect(0, 0, 400, canvas.height);
        ctx.strokeStyle = "#FAA";
        ctx.stroke();

        ctx.globalAlpha = 1;
        ctx.fillStyle = "#FFF";
        ctx.font = "30px Ubuntu";
        ctx.fillText("Leaderboard", 100 - ctx.measureText("Leaderboard").width / 4, 40);

        if (leaderboard.type === "pie") {
            var last = 0;
            for (var i = 0; i < len; i++) {
                ctx.fillStyle = leaderboard.teams[i];
                ctx.beginPath();
                ctx.moveTo(100, 140);
                ctx.arc(100, 140, 80, last, (last += leaderboard.items[i] * PI_2), false);
                ctx.closePath();
                ctx.fill();
            }
        } else {
            var text, isMe = false, w, start;
            ctx.font = "20px Ubuntu";
            for (var i = 0; i < len; i++) {
                if (leaderboard.type === "text")
                    text = leaderboard.items[i];
                else
                    text = leaderboard.items[i].name,
                    isMe = leaderboard.items[i].me;

                // replace {skin} with empty string
                var reg = /\{([\w]+)\}/.exec(text);
                if (reg) text = text.replace(reg[0], "").trim();

                ctx.fillStyle = isMe ? "#FAA" : "#FFF";
                if (leaderboard.type === "ffa")
                    text = (i + 1) + ". " + (text || "An unnamed cell");
                var start = ((w = ctx.measureText(text).width) > 15) ? 5 : 200 - w * 0.4;
                ctx.fillText(text, start, 70 + 25 * i);
            }
        }
    }


------------


4) Paste it in place for code deleted in step 2. 


**NOTE: If you just want the leaderboard left aligned but no the agar.io style, Just Change the width.** 

Hope This Helps! 💯

**Comment by cowpits** [comment]
Thank you @CodeFlush I have my width set to 250, default was 200 the rest of the code is on par with what you posted. except for these lines, I have this:
	ctx.globalAlpha = .00;
        ctx.fillStyle = "#000";
        ctx.fillRect(0, 0, 250, canvas.height);

you have this: 
   ctx.globalAlpha = .4;
    ctx.fillStyle = "#000";
    ctx.fillRect(0, 0, 400, canvas.height);
    **ctx.strokeStyle = "#FAA";
    ctx.stroke();**

I don't have the bolded line. 
I'll change the width to 300. I just want the names to align to the left, currently they're like this: https://i.imgur.com/b56DHp7.png

**Comment by Tetratrix** [comment]
@CodeFlush Can you help me with the skins please?

**Comment by Pollogy** [comment]
Cowpits- bolded lines do not do nothing it was a experiement by me which failed, remove it 

Tetratrix-Yes tomorrow alrt? It’s night... Also, I have gotten this to work for my client, which is modified , so i will test it on base , aka this, and if it works I will definitely share the code, and might create a PR bcz this is really useful.

**Comment by Pollogy** [comment]
^^^ same person

**Comment by MiraMiPalo** [comment]
@Tetratrix  in index.html
change your play button for this
 `<button type="button" id="play-btn" onclick="play(document.getElementById('skininput').value + document.getElementById('nick').value); return false;" class="btn btn-play btn-primary btn-needs-server">Play</button>`

and add this line
`<input id="skininput" class="form-control save" data-box-id="1" placeholder="Skin" maxlength="115" />`

**Comment by Pollogy** [comment]
Yea ^^ he helped me with skin thing

**Comment by cowpits** [comment]
@Pollogy the bolded lines are the ones I don't have lol. Thanks though.

**Comment by cowpits** [comment]
I think I got it, which one is better? left or right please? 
https://i.imgur.com/Gfxk7Cq.png

**Comment by cowpits** [comment]
OK, I'm settled, I think I like this;  https://i.imgur.com/eW1YFtD.png
changed to align left, changed font to 18px, changed line spacing to 22px, changed canvas width to 250.

canvas.width = **250**; // default was 200

ctx.globalAlpha = **.00**; // so it's transparent, default was .04

 ctx.font = "**18px** Ubuntu"; // default was 20px

to align left: 
var start = ((w = ctx.measureText(text).width) > 200) ? **2 : 0 - w * 0**;  // default was  2 : 100 - w * 0.5;

name spacing:
ctx.fillText(text, start, 70 + **22** * i) // default was ctx.fillText(text, start, 70 + 24 * i);

**Comment by cowpits** [comment]
compare https://i.imgur.com/zjdCm2P.png

**Comment by CodeFlush** [comment]
Wait so the code i sent above did not work? @cowpits

**Comment by bradennss** [comment]
you people are idiots

**Comment by bradennss** [comment]
making agar.io clones for your clan is a mistake

**Comment by cowpits** [comment]
@CodeFlush I didn't try it but my comparison was pretty much the same as I had. Unless I'm missing something.

**Comment by CodeFlush** [comment]
Dont you have a game too, chewy

**Comment by cowpits** [comment]
@chewythepig thanks for contributing with something useful.

**Comment by CodeFlush** [comment]
@cowpits its good, all good

**Comment by bradennss** [comment]
@CodeFlush yes i do

**Comment by bradennss** [comment]
@cowpits you’re welcome

**Comment by CodeFlush** [comment]
Isnt that almost the same thing

**Comment by CodeFlush** [comment]
This is a open source project, he can use it how he like, does this project restrict you from using this for your clan? as far as I know.... No. He can use it how he likes, I mean how can you say such thing when you are running a game based on the cloning of agar.io? 👎

**Comment by bradennss** [comment]
@CodeFlush you haven’t exactly won the argument by pointing out in a hypocrite, my point is it’s a waste of time and money hosting and developing an agario clone for a clan, that more than likely will die off or be disbanded in less than a month.

**Comment by cowpits** [comment]
GKClan has been around close to 2 years, they have 340+ members. On average we have 24 players on the server. I see your point about time and money but the clan is a hobby and it does very well with 6 moderators, 2 admins, and 1 dev. So it dies big deal. But to call people stupid for doing something you don't agree with is itself ignorant. But anyway here are the site stats http://www.histats.com/viewstats/?SID=3882226&f=2

**Comment by cowpits** [comment]
@CodeFlush I tried your code and this is what I got https://i.imgur.com/NnDDP0H.png
thank you it works. 
I guess I'm trying to understand the math at this line: 
You have this, which aligns left : var start = ((w = ctx.measureText(text).width) > 15) ? 5 : 200 - w * 0.4;
Cigar has this, which aligns center: var start = ((w = ctx.measureText(text).width) > 200) ? 2 : 100 - w * 0.5;
I did this, to align left, var start = ((w = ctx.measureText(text).width) > 200) ? **2 : 0 - w * 0;**
In essence all I needed to do was figure out the math to align left, your code already has it but I didn't use it because of all the other edits that I have, too lazy to redo it all. When all I needed was to copy the line **var start = ((w = ctx.measureText(text).width) > 15) ? 5 : 200 - w * 0.4;** 
lol I feel dumb and should have tried it, instead of wasting an hour trying to figure it for myself. But I appreciate your help thank you. I guess the trick that I was looking for was simply that line.

**Comment by Pollogy** [comment]
@cowpits I messed with the code here and there so sorry, Multiple changes have been made to those line to fit my liking, sorry I wasted your time. 



@chewythepig  I don't want start off on the wrong foot here I admire your work and stuff but, @cowpits is doing what he likes and is getting support from his fellow subscribers and clan members, he enjoy what he does, but what you did there, that comment "you people are idiots, making agar.io clones for your clan is a mistake" was highly unnecessary. I mean how can  you say that when you are  running a website based off of it, as I already said before. Let him do what he wants, its not like he is asking you to pay for his hosting or whatever, all he did was made and issue and asked for help, you shouldn't just come and make a comment that isn't really helping or contributing to the issue whatsoever.

**Comment by CodeFlush** [comment]
@cowpits I messed with the code here and there so sorry, Multiple changes have been made to those line to fit my liking, sorry I wasted your time. 



@chewythepig  I don't want start off on the wrong foot here I admire your work and stuff but, @cowpits is doing what he likes and is getting support from his fellow subscribers and clan members, he enjoy what he does, but what you did there, that comment "you people are idiots, making agar.io clones for your clan is a mistake" was highly unnecessary. I mean how can  you say that when you are  running a website based off of it, as I already said before. Let him do what he wants, its not like he is asking you to pay for his hosting or whatever, all he did was made and issue and asked for help, you shouldn't just come and make a comment that isn't really helping or contributing to the issue whatsoever.

**Comment by cowpits** [comment]
Thank you @CodeFlush what you said means a lot to me. I honestly feel that sometimes all my efforts go unnoticed, given that I get 1000's of views and no subs but besides that YouTube hasn't paid me lol. But I'm not doing this for the money, it's just a hobby that's all. I'm an IT pro and if I can help others then why not? 
My Skype and Discord are full of requests waiting on me. I have built 1000's of servers for people and sites for them to play on. I know it's a lot and it's a lot of work on my part but they're kids who want to stream and play with their friends and if I have the time I do it no questions asked. 
Anyway, thank you for your kind words and noticing my efforts. I do truly appreciate it.

**Comment by bradennss** [comment]
Fair enough, apologies for the rude comments @cowpits and @CodeFlush.

**Comment by bradennss** [comment]
@cowpits For a proper comparison to your stats... https://imgur.com/a/EBJz8
EDIT: I’ll start trying Histats, looks more useful for the public, thanks for referring me to it.

**Comment by Pollogy** [comment]
Alright.. I hope this will be setelled

**Comment by CodeFlush** [comment]
@chewythepig alrighty! :D

**Comment by cowpits** [comment]
@chewythepig no worries man, thank you. I love your popsplit.us really nice.
