### ISSUE TITLE
should i share my (leveling-coins/ with facebook sdk) system ?

### ISSUE THREAD

**Issue by zettabyte918** [Luka967/Cigar#110]
school kill me now i can do nothing
i work so hard to make it 
if anyone want idk to improve it maybe !
![capture](https://user-images.githubusercontent.com/18426424/33387949-7da716a8-d526-11e7-8503-f8c9b364f6fe.PNG)
![capture](https://user-images.githubusercontent.com/18426424/33387994-992d626a-d526-11e7-90fd-e2901254e1a6.PNG)

**Comment by cowpits** [comment]
It would be nice to have but sharing is up to you. Looks very similar to agario though.

**Comment by bradennss** [comment]
I wrote a master server that acts as a web server and handles accounts, parties, and other related features of the game. It’s written in Node.js and communicates with clients via HTTP_UPGRADE (Web Sockets).

**Comment by ghost** [comment]
Yes, this would be extremely useful.

**Comment by cowpits** [comment]
@chewythepig is the master server available for sharing? I understand if not otherwise.

**Comment by bradennss** [comment]
@cowpits Definitely not.... sorry.

**Comment by cowpits** [comment]
@chewythepig lol no problem I understand. Teaser! lol :P j/k
