### ISSUE TITLE
Feature-request: Show scores in the leaderboard

### ISSUE THREAD

**Issue by SuperOP535** [Luka967/Cigar#111]
Leaderboard
1. SuperOP535 - 10.4k
2. Someone - 9.1k

Similar to diep.io
If u added a way to choose if it would be like 10.4k or 10412 that would be cool

**Comment by bradennss** [comment]
@SuperOP535 This would also be a server side modification, as you would have to send scores along with player names in leaderboard update packets.

**Comment by ghost** [comment]
@SuperOP535  Close?

**Comment by MiraMiPalo** [comment]
@chewythepig  Not Server Side!

**Comment by bradennss** [comment]
@MiraMiPalo Yes, it is server side. The client needs to know the mass of the players on the leaderboard, without having to find their mass by rendering their cell. This requires extra information to be sent by the server in leaderboard update packets.

**Comment by Luka967** [comment]
^

**Comment by bradennss** [comment]
👍
