### ISSUE TITLE
Feature-request: Coordinates

### ISSUE THREAD

**Issue by SuperOP535** [Luka967/Cigar#112]
I remember an old private server called agarly and it had this, like X 100 Y 86.

If possible add to settings so it can be disabled 😃

**Comment by bradennss** [comment]
@SuperOP535 Sorry to be blunt, but you just need to learn JavaScript. Luka adds what is important to the project, or fixes already introduced issues. I don’t really think he accepts feature request, but someone might be willing to do this.

**Comment by SuperOP535** [comment]
I know JavaScript.. I'm just asking this so everyone can get use of this if it gets made. If I want I will most likely be able to make one myself

**Comment by SuperOP535** [comment]
Now you are most likely going to say: why don't you pull request.
Well maybe I will do if I succeed lol

**Comment by bradennss** [comment]
@SuperOP535 Make a fork and write it yourself then if you can, then create a merge request.

**Comment by bradennss** [comment]
Sheesh I’ll just create one.

**Comment by SuperOP535** [comment]
So you are adding this? to your own fork

**Comment by bradennss** [comment]
@SuperOP535 https://github.com/Luka967/Cigar/pull/113

**Comment by SuperOP535** [comment]
Wow that was quick lol tysm, closing this now
