### ISSUE TITLE
Bug with an older version of MultiOgar-Edited

### ISSUE THREAD

**Issue by Tetratrix** [Luka967/Cigar#114]
that happens after having opened the server a few minutes, and also the cells do as teleportation. please help
I am using multiogar edited since the function of setColor () was replaced by color

![screenshot_1](https://user-images.githubusercontent.com/33761802/33462190-34ccfe82-d604-11e7-97b0-5a27566c02a1.png)

**Comment by CodeFlush** [comment]
@Tetratrix  Whats ur site?

**Comment by Tetratrix** [comment]
i no have a site, im testing in localhost

**Comment by CodeFlush** [comment]
@Tetratrix  is it this client?

**Comment by Tetratrix** [comment]
yes, is cigar client, why?

**Comment by Luka967** [comment]
Exactly which version are you using? And have you modified the client's main_out?

**Comment by Tetratrix** [comment]
MultiOgar-Edited 1.6 and yes, but they aren't big changes
