### ISSUE TITLE
need help with skins

### ISSUE THREAD

**Issue by alktbihd** [Luka967/Cigar#12]
how can i load the skins?

**Comment by Luka967** [comment]
Skins aren't drawn on cells for now.
If you still want to load skins, check the readme.

**Comment by alktbihd** [comment]
http://35.156.68.17/ its showing me a white screen for some reason

**Comment by Luka967** [comment]
Sorry for not responding.
Replace `reader.js`, `main_out.js` and `index.html` with newly updated versions. Should fix everything.

**Comment by Luka967** [comment]
Closing this.
