### ISSUE TITLE
How can I modify the minimum zoom? ( so i can zoom out more )

### ISSUE THREAD

**Issue by SuperOP535** [Luka967/Cigar#120]
in original cigar there is a function called calcViewZoom but searching for zoom in this one gives no results.. may i ask why the code here is obfuscated-like when the original has understandable function names and stuff?

**Comment by ItzLevvie** [comment]
@SuperOP535 https://github.com/Luka967/Cigar/blob/master/www/assets/js/main_out.js#L858-L890

**Comment by cowpits** [comment]
if you want to zoom out like I have on http://gkclan.me look for this line 1153:
1 > mouseZ && (mouseZ = 1);
to make it zoom out to a stop point like on my site then change the 1's to 0.2 so you'll have this:
0.2 > mouseZ && (mouseZ = 0.2);

if you want unlimited zoom just rem the line with // and you'll have this:
// 1 > mouseZ && (mouseZ = 1);

**Comment by cowpits** [comment]
@ItzLevvie is that for the name to show in minimap? if so, nice I need to add then.

**Comment by SuperOP535** [comment]
@cowpits check out the latest commit https://github.com/Luka967/Cigar/commit/c1addedc38b78cda461f1226d7f14359789a0d72

**Comment by SuperOP535** [comment]
@cowpits thank you so much! now i can finally zoom out when im big 😃
