### ISSUE TITLE
Hide Chat bug

### ISSUE THREAD

**Issue by cowpits** [Luka967/Cigar#121]
@Luka967 I noticed when Hide Chat is selected it only takes away the ability to post a message but chat messages from others still appear. 
Can you help please?

**Comment by MiraMiPalo** [comment]
**down of this line** https://github.com/Luka967/Cigar/blob/c1addedc38b78cda461f1226d7f14359789a0d72/www/assets/js/main_out.js#L838

**add this**  `if (!settings.showChat) mainCtx.globalAlpha = 0;`

**works for me**

**Comment by cowpits** [comment]
@MiraMiPalo thank you works great. Can this be added to a commit?

**Comment by Luka967** [comment]
I'll do it when on Sunday, I gotta reinstall my OS

**Comment by cowpits** [comment]
Thank you @Luka967
