### ISSUE TITLE
No names remains ticked after refresh

### ISSUE THREAD

**Issue by SuperOP535** [Luka967/Cigar#126]
how to reproduce:
1. tick no names
2. refresh
3. untick no names
4. refresh

expected result:
it remains unticked

actual result:
it gets ticked

**Comment by cowpits** [comment]
yes it keeps the option ticked, after you untick and refresh then it throws the error. Nice find 👍

**Comment by Tombez** [comment]
Has this been fixed? Could not reproduce with those steps...
Edit:
I'm using latest version of Chrome
Also seems to work correctly in latest Firefox as well

**Comment by bradennss** [comment]
Never experienced this problem, although i used a different method for rendering checkboxes and listening for changes.

**Comment by SuperOP535** [comment]
This has been fixed at Cigar2 https://github.com/Cigar2/Cigar2
