### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Fan7asy** [Luka967/Cigar#127]
Why don't you make this non-php dependent?

**Comment by chewythepig** [comment]
I can help with this please I love the thought of removing PHP from the scope of this shit.

**Comment by Luka967** [comment]
There needs to be a way of getting all the filenames in /skins, and PHP is the best solution for that. It's up to others to remove the PHP request.

**Comment by chewythepig** [comment]
Wrap the client in a Node.js webserver.

**Comment by Niall7459** [comment]
@chewythepig The old cigar client used to be a models web server but they removed it and made it client only. I think in Luke’s repository’s look for CigarOld

**Comment by Niall7459** [comment]
Nodejs not models
