### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by SuperOP535** [Luka967/Cigar#130]
The updated version of cigar with the new todo list is located here: https://github.com/Cigar2/Cigar2

**Comment by Tombez** [comment]
Isn't server uptime already implemented?

**Comment by SuperOP535** [comment]
@Tombez It seems like I were blind XD, removed from the list

**Comment by agarian-2** [comment]
I have no clue how to add my map border line, or coordinate feature to Luka's client (too difficult lol).
Time alive should be easy, but IDK.
Unsure about the minimap thing, or the chat scrolling.
Is anybody even gonna use that on mobile?
And `save gameserver`??

**Comment by SuperOP535** [comment]
@agarian-2 Ok so I've already made border line for my server and rn I'm working on time alive, coordinates are hard ikr.. Chat scrolling is easy ( I'm also working on it right now ) And the save gameserver is like if you choose FFA it saves it in localStorage so next time you open the game it automatically chooses FFA. And about the mobile.. yes, people play on mobile and it would be a nice addition to have

**Comment by Tombez** [comment]
Created pull request ~~#139~~ #142  that draws all of the player's cell on the minimap.

**Comment by Agarian** [comment]
I got coordinates down

**Comment by SuperOP535** [comment]
https://github.com/Cigar2/Cigar2
