### ISSUE TITLE
An error with Luka!

### ISSUE THREAD

**Issue by SuperOP535** [Luka967/Cigar#144]
@Luka967 Why don't you merge these a w e s o m e open pull requests?? https://github.com/Luka967/Cigar/pulls

**Comment by SuperOP535** [comment]
why am I even bothering I will just merge them to a new fork

**Comment by SomeoneCares11** [comment]
yes please!

**Comment by SuperOP535** [comment]
I've done that already I (github/Cigar2/Cigar2) but I haven't pushed just yet
