### ISSUE TITLE
Thank you so much.

### ISSUE THREAD

**Issue by mrzack506** [Luka967/Cigar#16]
You built this from scratch, and you aren't charging anyone for it, like 99% of the population would. 
I just want to say thanks, for contributing this great effort to the Cigar client, as the few that are in the Cigar project thank you greatly. 

Again, thanks. 

P.S, 
Cell jiggles are non-existent as of right now, so how would smooth render work (other than resolution downscale)?

**Comment by Luka967** [comment]
Cell jiggles exist but they're far from vanilla-like. I need to go deep into the old client's code to see its animation style.
