### ISSUE TITLE
SmoothRender

### ISSUE THREAD

**Issue by PsycoYT** [Luka967/Cigar#18]
hello , good work!

I come to ask about the smoothrender, what happens to that?

**Comment by Luka967** [comment]
The same as with vanilla, cells vibrating.
Currently perfecting the animation.

**Comment by PsycoYT** [comment]
I mean the effect when the cell grows

**Comment by Luka967** [comment]
I don't know which effect are you talking about.

**Comment by PsycoYT** [comment]
see the video when the cells grows

https://www.youtube.com/watch?v=y43WRajm8lA

Fix when the cell grows

**Comment by Luka967** [comment]
He uses an extension which animates cell size more slowly.

**Comment by PsycoYT** [comment]
In agar.io this effect is until when you divide in 8 and as approxidamente until 3000 of mass

**Comment by Luka967** [comment]
Nice spotting, will implement soon

**Comment by Luka967** [comment]
did it

**Comment by PsycoYT** [comment]
implemented?

**Comment by Luka967** [comment]
Yes
