### ISSUE TITLE
last update

### ISSUE THREAD

**Issue by PsycoYT** [Luka967/Cigar#22]
the last update have a 
Sudden rises of ping

**Comment by Luka967** [comment]
Ping is checked every two seconds by measuring time when packet 254 was sent and receieved (when server stats, top left, was requested an update). The server should respond immediately upon receiving the packet. If your server is lagging (>40ms update time) the server won't respond fast, however that extra response time does count.

Client also won't check for ping if server doesn't respond with server version on first packet 64 (ie when you connect), or got a version that doesn't have "MultiOgar" anywhere in it.
