### ISSUE TITLE
Skins

### ISSUE THREAD

**Issue by alktbihd** [Luka967/Cigar#23]
Skins won't load for some reason

**Comment by Luka967** [comment]
I've forgot to put a fix for `checkdir.php`, check in 5 minutes to see if it fixes the problem.

**Comment by PsycoYT** [comment]
If they worked, in fact they do not work now .. try ogar.pw

**Comment by Luka967** [comment]
@PsycoYT `checkdir.php` call on your site responds with nothing. Do you have PHP on your webserver?

**Comment by PsycoYT** [comment]
the error is you replaced 

` if (settings.showSkins && skin != '') {`

for 

`if (settings.showSkins && skin != '' && -1 !== knownSkins.indexOf(skin)) {`

**Use || instead &&**


THERE IS THE ERROR ... I AM FIXED .. ogar.pw

**Comment by PsycoYT** [comment]
The only problem is that you can not draw the skin name apart. example:

{Hello nigh}

**Comment by Luka967** [comment]
Even && would work if checkdir.php returned properly, but whatever

**Comment by PsycoYT** [comment]
&& not working for me.

**Comment by PsycoYT** [comment]
![image](https://cloud.githubusercontent.com/assets/24230169/21702682/aa6ef978-d38b-11e6-89e4-c63a6c881379.png)


bug when i replaced the funcion viewMultiplier to
```

 function viewMultiplier() {
        return Math.max(mainCanvas.height / 3080, mainCanvas.width / 3920);
    }
```

see the score draw

**Comment by PsycoYT** [comment]
pd: 
I've already eliminated the problem.
