### ISSUE TITLE
hide chat

### ISSUE THREAD

**Issue by PsycoYT** [Luka967/Cigar#25]
when i active the option hide chat nothing happens

**Comment by Luka967** [comment]
Will fix now

**Comment by Luka967** [comment]
Actually your main_out is outdated.

**Comment by PsycoYT** [comment]
i think the ChatTextbox need '#' jquery indicator to be removed

in hidechat function

**Comment by Luka967** [comment]
As I said your main_out.js is old, the new one has this fixed...

**Comment by PsycoYT** [comment]
Chat_textbox is not hidden

**Comment by Luka967** [comment]
Nothing can't be sent
