### ISSUE TITLE
color of cell depending skins

### ISSUE THREAD

**Issue by PsycoYT** [Luka967/Cigar#26]
To look more like agar.io

This if it does not work since there is some function that does as if it were not in the name, what should I do?

```
 if (this.name.indexOf("{alpaca}") !== -1) {
					
					  mainCtx.fillStyle = "#F4F010";
					  mainCtx.strokeStyle = "#A3A00B";
					
				
				}
```

Otherwise without the {} in the if, only "alpaca" bone, if it works

**Comment by Luka967** [comment]
Useless check. The only thing that would be changed is the cell's outline color, and nobody pays attention to it.
