### ISSUE TITLE
hm is better?

### ISSUE THREAD

**Issue by PsycoYT** [Luka967/Cigar#32]
**Spatial hash is better than qtree?**

http://zufallsgenerator.github.io/2014/01/26/visually-comparing-algorithms/

`Now I could easily compare both algorithms. To me, was pretty obvious that spatial hashing was more efficient. This was also shown as I plugged in my spatial hash implementation - the performance problem were greatly reduced and I could have 80 objects without the collision detecting became a bottle neck.`

**Comment by Luka967** [comment]
Quadtree isn't even used for now.
