### ISSUE TITLE
ANTI SPAM CHAT

### ISSUE THREAD

**Issue by PsycoYT** [Luka967/Cigar#34]
please make it !

**Comment by AlexDicy** [comment]
PLEASE DELETE YOUR GITHUB ACCOUNT, thanks sir.

**Comment by Luka967** [comment]
You've also asked it in [MultiOgar-Edited](https://github.com/Megabyte918/MultiOgar-Edited/issues/359), and ZfsrGhS953 gave you a 2 minute fix.
