### ISSUE TITLE
bad :(

### ISSUE THREAD

**Issue by PsycoYT** [Luka967/Cigar#39]
I had to take out your client :( because when I give a lot I get a lot of lag, which does not happen in protocol 5 cigar

**Comment by Luka967** [comment]
Lag when you give a lot of what? W? Cells? Skins lagging?

**Comment by PsycoYT** [comment]
I love your client, but they give sudden flashes of lag, please fix the performance and I'll implement it on my server, it's pretty good, thanks.

**Comment by Luka967** [comment]
What do you do when it starts lagging? When does it lag? How many cells are on the screen, approximately? I can't fix bugs while blind

**Comment by PsycoYT** [comment]
Currently there is no lag in the new update, I will tell you anything.

**Comment by Luka967** [comment]
Well great thanks for adding an useless issue and wasting my time.
