### ISSUE TITLE
Party system

### ISSUE THREAD

**Issue by RelTakeover** [Luka967/Cigar#43]
Could it be possible to add a party system? As in gota.io It would be revolutionary, and everyone would use your client

**Comment by Luka967** [comment]
Requires prototocol modifications

**Comment by RelTakeover** [comment]
Do not think you need to, jaralowell has created a map where you can see the other players on the map with your protocol.

**Comment by Luka967** [comment]
![this](https://cloud.githubusercontent.com/assets/15956695/21897216/3bebd972-d8e9-11e6-83aa-108b60cbb49f.JPG)
Jara used a protocol modification.

It doesn't actually need to, but needs a server somewhere which needs a protocol (again) to receive and send out position messages.

**Comment by ArixProject** [comment]
`case 0x68:
var temp= setTimeout(function () {
// Minimap Draw
var k = border.right * 2;
var j = border.bottom * 2;
var a = document.getElementById("nodes");
a.width = 200;
a.height = 200;
var mCtx = a.getContext("2d");
mCtx.clearRect(0, 0, 200, 200);
mCtx.globalAlpha = 1;
while (1) {
 var id = reader.getUint32():
 if (0 === id) break;`

**Comment by bradennss** [comment]
How are you going to get those player positions *without* a protocol modification? The answer is... you wont.

**Comment by bradennss** [comment]
That is unless you decide to only track cells that are already being rendered by the client (for example, all of the cells that are in the field of view).
