### ISSUE TITLE
game stutters

### ISSUE THREAD

**Issue by Niall7459** [Luka967/Cigar#44]
Significantly more stuttering lagging on this than original Cigar.

2 Bots.
1 Player.
MultiOgar-Edited latest 10 JAN 2017 - 17:22

**Comment by Luka967** [comment]
FPS stutters or center position stutter?

**Comment by Niall7459** [comment]
not sure how to describe, it includes food as well.
![cigarlag](https://cloud.githubusercontent.com/assets/9781846/21820906/71038df2-d769-11e6-929b-a857312a4cf5.gif)

**Comment by Luka967** [comment]
It's center position stutter. It's probably because of drawing and updating happening at the same time.
I've just got a solution in my head and will fix this now

**Comment by Niall7459** [comment]
Ah ok nice, thank you.

This client looks amazing, I'm going to upgrade!!

**Comment by Luka967** [comment]
Just screwed up real hard, need to start from scratch xD

**Comment by Luka967** [comment]
Also it isn't because of drawing & updating at same time. I need to debug really deep for this.

**Comment by Luka967** [comment]
I'm still not able to find the reason of this.

**Comment by Niall7459** [comment]
Ok.

**Comment by Niall7459** [comment]
IT must be something that hase changed from original cigar.. because not happens on normal cigar.

**Comment by Luka967** [comment]
I've kind of stopped updating this client... bugs will probably exist for a long time

**Comment by Luka967** [comment]
wait didn't mean to close lol

**Comment by Luka967** [comment]
I've finally fixed this. Pushing updates soon

**Comment by Niall7459** [comment]
Nice thanks, by today?

**Comment by Luka967** [comment]
Already pushed them xD

**Comment by Luka967** [comment]
See commit f0a8e9d

**Comment by Niall7459** [comment]
It is improved but still not as good as cigar
