### ISSUE TITLE
Cigar must be Responsive

### ISSUE THREAD

**Issue by SomeoneCares11** [Luka967/Cigar#46]
Hi,

i'm using 34inch screen, my problem with the overlays & cells .. see below, 

![Image](http://i.imgur.com/RqwqqeT.png)

i don't get these problem in official agar.io ,old cigar and JaraLowell's client

**Comment by Luka967** [comment]
A quick fix away, give me a few minutes

**Comment by Luka967** [comment]
fixed

**Comment by SomeoneCares11** [comment]
still !

cigar : 
http://i8.ae/eBuhF

agar.io:
http://i.imgur.com/O4bqeSD.png
