### ISSUE TITLE
Where is that function?

### ISSUE THREAD

**Issue by RelTakeover** [Luka967/Cigar#54]
Where is the function that hide the skinName in the nick of the cell?

**Comment by Luka967** [comment]
[Here](https://github.com/Luka967/Cigar/blob/master/www/assets/js/main_out.js#L1220-L1225)

**Comment by RelTakeover** [comment]
how to delete thhis function without affect skins?

**Comment by RelTakeover** [comment]
how to detele hide skinName without affect the skins?
