### ISSUE TITLE
how to ?

### ISSUE THREAD

**Issue by RelTakeover** [Luka967/Cigar#58]
how to put color clans? if i put in my name "YT" in the leaderbord changes the color ...

```
if (this.name.indexOf("yt") !== -1 || this.name.indexOf("YT") !== -1) {
			ctx.fillStyle = me ? "#FFAAAA" : "#FFAAAA";
  
		}

```
in drawleaderboard function correct?

**Comment by Luka967** [comment]
FFS stop posting issues related to customization. Do it youself.
