### ISSUE TITLE
Where are the cell animations?

### ISSUE THREAD

**Issue by mrzack506** [Luka967/Cigar#62]
https://streamable.com/u1h1o

No split animation, the client just feels like an improved smooth render for this:
https://streamable.com/5tq4e

**Comment by Luka967** [comment]
I've tried mimicking the agar cell animation as much as possible without creating a lot of stress to the client.
I also have zero idea how does [cell animation section of code](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L1246-L1288) in protocol 5 Cigar work and I didn't even try doing deep into it.
It's not even improved - if you zoom in really close in, you'll see that it's spongy-like.
I've kind of stopped updating this project so you might not see an integration with the old point collision any time soon.
