### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by gyeyoqu** [Luka967/Cigar#66]
when i try edit something it says me "the variable is not defined" , but the variable is defined but above , how to fix?

**Comment by ItzLevvie** [comment]
I suggest Notepad++ for editing JavaScript files

**Comment by Luka967** [comment]
What are you actually talking about?

**Comment by ItzLevvie** [comment]
@gyeyoqu Show screenshots to describe your issue or elaborate.....

**Comment by gyeyoqu** [comment]
I have been learning javascript. If I edit a line and that line has a variable and that variable is defined, but very far from what I'm editing, it tells me that the variable is not defined, it's a javascript problem, but how is it solved?

**Comment by Luka967** [comment]
Where exactly is the variable defined at?

**Comment by gyeyoqu** [comment]
if i add "if (admin) me = 'admin'  + me; in DRAWLEADERBOARDFUNCTION he says that the variable is not defined,  but te var is defined , but far
