### ISSUE TITLE
Know

### ISSUE THREAD

**Issue by gyeyoqu** [Luka967/Cigar#71]
Hello, I would like to know how to change the color of pellets and viruses, sorry for the inconvenience

**Comment by Luka967** [comment]
That's server-side.

**Comment by gyeyoqu** [comment]
Sorry but I have managed to change the colors of the virus, but not the food, help me please

**Comment by Luka967** [comment]
Random colors are defined [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/GameServer.js#L370-L381) in MultiOgar-Edited.

**Comment by gyeyoqu** [comment]
But that would also affect the color of the cell and I just want to change the food?

**Comment by gyeyoqu** [comment]
just as client ogarplus does

**Comment by gyeyoqu** [comment]
@Luka967  You can help me ,please.

**Comment by gyeyoqu** [comment]
thanks.
