### ISSUE TITLE
emoticons!!

### ISSUE THREAD

**Issue by gyeyoqu** [Luka967/Cigar#78]
emoticons not supported ! try put 💕 in ogar.pw

**Comment by Luka967** [comment]
Server-side non-ASCII checking is on. Turn off [`serverChatAscii`](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gameserver.ini#L64).

**Comment by gyeyoqu** [comment]
ALREADY TURN OFF !!

**Comment by ItzLevvie** [comment]
Change ```serverChatAscii = 1``` to ```serverChatAscii = 0```

If it's still not working, then it's a problem with your client.

**Comment by gyeyoqu** [comment]
Calm, I'm not retarded , Still not working and I'm using this client. try http://ogar.pw

**Comment by gyeyoqu** [comment]
They simply do not appear****

**Comment by ItzLevvie** [comment]
It's a client side problem, and we can't help you if you encrypted your JS

**Comment by gyeyoqu** [comment]
Here :  http://ogar.pw/js/im.js

**Comment by gyeyoqu** [comment]
and now ?

**Comment by Luka967** [comment]
It's a problem with the client. I've just checked it.

**Comment by gyeyoqu** [comment]
fixed?

**Comment by Luka967** [comment]
Fixed with commits 064cabf and 8ebdbcd
