### ISSUE TITLE
Mobile client

### ISSUE THREAD

**Issue by cowpits** [Luka967/Cigar#86]
how to get this to work with mobile devices? is it possible?

**Comment by Jhair2015** [comment]
Yes, is it possible

**Comment by cowpits** [comment]
I can connect to it on my phone but the split and feed buttons don't show. I see the .png files for them in /img directory but i'm missing the control, it even picks up Mobil graphics settings. So I know it's possible but it's not working.

**Comment by Luka967** [comment]
They're not even rendered. There's no logic for the buttons nor the joystick.

**Comment by cowpits** [comment]
Thank you
