### ISSUE TITLE
line ?

### ISSUE THREAD

**Issue by plazo123** [Luka967/Cigar#96]
what line dose the chat conntact with multiogar fotr chat commands and stuff
issue im not sure tbh

**Comment by gyeyoqu** [comment]
the function wsMessage is that Receive all packages

**Comment by plazo123** [comment]
where is that located ? 
and how can i add the connect code to http://plazo.esy.es/test2 for server sided chat @gyeyoqu

**Comment by plazo123** [comment]
@gyeyoqu yes where is that
