### ISSUE TITLE
what about Gold system !

### ISSUE THREAD

**Issue by zettabyte918** [Luka967/Cigar#99]
I see that many website add this system, so how this work , and how they can detect id of player on client side ?

**Comment by ArixProject** [comment]
System of what?

**Comment by zettabyte918** [comment]
example whene u eat 10 food then u have one gold and with this gold it can give you 30 mass when you click "Z" u understand me ?
example http://bomb.agar.bio/

**Comment by bradennss** [comment]
You would need protocol modifications/account system of your own.

**Comment by zettabyte918** [comment]
thnx but already make this its easy and i make start mass with facebook login but now  im working for mass boost
